
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umi_shop_auth
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

  security:
    oauth2:
      client:
        mode: 'sandbox'
        registration:
          paypal:
            clientId: AYQwg1YezCe92zHxmpD8Y8q6M3_AbaGYpjs--ATI3WZzYBdcupomPY3L5lO91mdnv48iYjD6FQ41_QwE
            clientSecret: ECbVzUVjhR2Pu_x5PYeXGvmcBnQWK-9sJe1T5D-TlfwJwuXplM666HmJH9A8pvvjkU0UgvftWkSzw23b
            redirectUri: "https://880d-66-253-183-231.ngrok-free.app/login/oauth2/code/paypal"
            authorizationGrantType: authorization_code
#            scope: openid, email, profile
        provider:
          paypal:
            authorizationUri: https://www.sandbox.paypal.com/signin/authorize
            tokenUri: https://api.sandbox.paypal.com/v1/oauth2/token
            userInfoUri: https://api.sandbox.paypal.com/v1/identity/oauth2/userinfo
            userNameAttribute: name

server:
  port: 9002

security:
  jwt:
    token:
      secret-key: MUUqkTMQiACw7o84UUjKy8mYT4DtYgjNfvqu/VbyxZw=
      expire-length: 3600000 # 1 hour
